import { useCallback, useEffect, useState } from 'react';
import { Check, Search } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { api, type Incident, type IncidentPatterns, type IncidentStatistics } from '../../services/api';

export default function Incidents() {
  const [incidents, setIncidents] = useState<Incident[]>([]); const [stats, setStats] = useState<IncidentStatistics | null>(null); const [patterns, setPatterns] = useState<IncidentPatterns | null>(null);
  const [selected, setSelected] = useState<Incident | null>(null); const [filters, setFilters] = useState({ service_name: '', severity: '', root_cause: '' }); const [loading, setLoading] = useState(true); const [updating, setUpdating] = useState(false); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null); const navigate = useNavigate();
  const load = useCallback(async () => { setLoading(true); try { const [all, statistics, aggregate] = await Promise.all([api.getIncidents(), api.getIncidentStatistics(), api.getIncidentPatterns()]); setIncidents(all); setStats(statistics); setPatterns(aggregate); setSelected(current => current ? all.find(item => item.id === current.id) || null : all[0] || null); setError(null); } catch (requestError) { setIncidents([]); setStats(null); setPatterns(null); setSelected(null); setError(requestError instanceof Error ? requestError.message : 'Incident data is unavailable.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const search = async () => { setLoading(true); try { const response = await api.searchIncidents(filters); setIncidents(response.incidents); setSelected(response.incidents[0] || null); setError(null); } catch (requestError) { setIncidents([]); setSelected(null); setError(requestError instanceof Error ? requestError.message : 'Incident search failed.'); } finally { setLoading(false); } };
  const resolve = async () => { if (!selected) return; setUpdating(true); try { const response = await api.updateIncident(selected.id, 'Resolved'); setSelected(response.incident); setIncidents(current => current.map(item => item.id === selected.id ? response.incident : item)); setNotice('Incident status updated to Resolved.'); await load(); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Status update failed.'); } finally { setUpdating(false); } };
  return <div className="p-8 bg-background min-h-screen text-text-primary"><div className="max-w-7xl mx-auto space-y-6"><header className="border-b border-white/[.06] pb-5"><h1 className="text-2.5xl font-bold font-heading text-white">Incident Management</h1><p className="text-text-muted text-xs mt-1">Persisted incident records and supported status management.</p></header>
    {error && <div className="rounded-xl border border-white/15 bg-surface px-4 py-3 text-xs text-text-muted flex justify-between"><span>{error}</span><button onClick={() => void load()} className="text-primary font-semibold">Retry</button></div>}{notice && <p className="text-xs text-primary">{notice}</p>}
    <section className="grid grid-cols-2 lg:grid-cols-4 gap-3">{[['Open', stats?.open_incidents], ['High / Critical', stats?.high_severity_incidents], ['Resolved', stats?.resolved_incidents], ['Historical', stats?.total_incidents]].map(([label, count]) => <div className="bg-surface/80 border border-white/[.08] rounded-xl p-4" key={String(label)}><p className="text-[10px] uppercase tracking-wider text-text-muted">{label}</p><p className="text-xl font-bold text-white mt-2">{count ?? '—'}</p></div>)}</section>
    <section className="bg-surface/80 border border-white/[.08] rounded-2xl p-4 grid md:grid-cols-4 gap-3"><input value={filters.service_name} onChange={event => setFilters({ ...filters, service_name: event.target.value })} placeholder="Service" className="bg-background border border-white/[.08] rounded-lg px-3 py-2 text-xs"/><input value={filters.root_cause} onChange={event => setFilters({ ...filters, root_cause: event.target.value })} placeholder="Root cause" className="bg-background border border-white/[.08] rounded-lg px-3 py-2 text-xs"/><input value={filters.severity} onChange={event => setFilters({ ...filters, severity: event.target.value })} placeholder="Severity" className="bg-background border border-white/[.08] rounded-lg px-3 py-2 text-xs"/><button onClick={() => void search()} className="rounded-lg bg-primary text-background text-xs font-bold flex justify-center items-center gap-2"><Search className="h-4 w-4"/>Search</button></section>
    <section className="grid lg:grid-cols-5 gap-6"><div className="lg:col-span-3 bg-surface/80 border border-white/[.08] rounded-2xl overflow-hidden"><div className="p-4 border-b border-white/[.06] text-xs text-text-muted">Incident list · {loading ? 'Loading…' : incidents.length + ' records'}</div>{!loading && incidents.length === 0 && <p className="p-6 text-xs text-text-muted">No incidents found.</p>}<div className="divide-y divide-white/[.05]">{incidents.map(incident => <button key={incident.id} onClick={() => setSelected(incident)} className={'w-full text-left p-4 hover:bg-elevated/30 ' + (selected?.id === incident.id ? 'bg-primary/5' : '')}><div className="flex justify-between gap-3"><p className="text-sm text-white font-semibold">{'INC-' + String(incident.id).padStart(4, '0') + ' · ' + incident.service_name}</p><span className="text-[10px] text-accent">{incident.severity}</span></div><p className="mt-1 text-xs text-text-muted">{incident.root_cause}</p><p className="mt-2 text-[10px] text-text-muted">{incident.status} · {new Date(incident.timestamp).toLocaleString()}</p></button>)}</div></div>
      <aside className="lg:col-span-2 bg-surface/80 border border-white/[.08] rounded-2xl p-5">{selected ? <div className="space-y-4 text-xs"><p className="text-[10px] uppercase tracking-widest text-text-muted">Incident detail · historical record</p><h2 className="text-lg font-heading font-bold text-white">{'INC-' + String(selected.id).padStart(4, '0')}</h2>{[['Service', selected.service_name], ['Severity', selected.severity], ['Anomaly type', selected.anomaly_type], ['Root cause', selected.root_cause], ['Recommendation', selected.recommendation], ['Status', selected.status], ['Timestamp', new Date(selected.timestamp).toLocaleString()]].map(([key, value]) => <div key={key}><p className="text-text-muted">{key}</p><p className="text-white mt-1">{value}</p></div>)}<div className="flex flex-wrap gap-2 pt-2">{selected.status !== 'Resolved' && <button disabled={updating} onClick={() => void resolve()} className="px-3 py-2 rounded-lg bg-primary text-background font-bold disabled:opacity-40 flex gap-1"><Check className="h-4 w-4"/>{updating ? 'Updating…' : 'Resolve'}</button>}<button onClick={() => navigate('/ai-simulator')} className="px-3 py-2 rounded-lg border border-accent/30 text-accent font-bold">Simulate recommended action</button></div></div> : <p className="text-xs text-text-muted">Select an incident to inspect its supported details.</p>}</aside></section>
    <section className="bg-surface/80 border border-white/[.08] rounded-2xl p-5"><p className="text-[10px] uppercase tracking-widest text-text-muted">Pattern context</p>{patterns ? <div className="mt-3 grid md:grid-cols-3 gap-3 text-xs"><p>Most common root cause: <span className="text-white">{patterns.most_common_root_cause || 'No pattern data available'}</span></p><p>Most affected service: <span className="text-white">{patterns.most_affected_service || 'No pattern data available'}</span></p><p>Recurring records: <span className="text-white">{patterns.recurring_incidents}</span></p></div> : <p className="mt-2 text-xs text-text-muted">No pattern data available.</p>}</section>
  </div></div>;
}
