import { useCallback, useEffect, useState } from 'react';
import { Play, RefreshCw, Sparkles } from 'lucide-react';
import { api, formatConfidence, type Metrics, type SimulationResult, type SystemStatus } from '../../services/api';

const actions = [
  ['scale_cpu', 'Vertical CPU Scaling'], ['scale_horizontal', 'Horizontal Scaling (Add Instances)'],
  ['reduce_latency', 'Request Queue Optimization & Caching'], ['restart_service', 'Graceful Service Restart'],
  ['optimize_memory', 'Memory Leak Fix & GC Tuning'], ['throttle_requests', 'Rate Limiting & Request Throttling'],
] as const;

export default function AISimulator() {
  const [metrics, setMetrics] = useState<Metrics | null>(null);
  const [status, setStatus] = useState<SystemStatus | null>(null);
  const [action, setAction] = useState<string>('scale_cpu');
  const [result, setResult] = useState<SimulationResult | null>(null);
  const [loading, setLoading] = useState(true);
  const [simulating, setSimulating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const loadCurrentState = useCallback(async () => { setLoading(true); try { const [nextMetrics, nextStatus] = await Promise.all([api.getMetrics(), api.getSystemStatus()]); setMetrics(nextMetrics); setStatus(nextStatus); setError(null); } catch (requestError) { setMetrics(null); setStatus(null); setError(requestError instanceof Error ? requestError.message : 'Current state is unavailable.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void loadCurrentState(); }, [loadCurrentState]);
  const simulate = async () => { if (!metrics || !status) return; setSimulating(true); setResult(null); try { const response = await api.simulateAction({ metrics: { cpu_usage: metrics.cpu, latency: metrics.latency }, action, context: { severity: status.severity, primary_issue: status.primary_issue, root_cause: status.root_cause } }); setResult(response.data); setError(null); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Simulation is unavailable.'); } finally { setSimulating(false); } };
  const selectedLabel = actions.find(([id]) => id === action)?.[1] || action;
  return <div className="p-8 bg-background min-h-screen text-text-primary"><div className="max-w-6xl mx-auto space-y-6">
    <header className="border-b border-white/[0.06] pb-5 flex flex-wrap gap-4 justify-between items-start"><div><h1 className="text-2.5xl font-bold font-heading text-white tracking-tight">What-If Remediation Simulator</h1><p className="text-text-muted text-xs mt-1">Evaluate the backend’s finite remediation actions against the current state.</p></div><span className="px-3 py-1.5 rounded-lg border border-accent/30 bg-accent/10 text-accent text-[10px] font-bold tracking-widest">SIMULATION ONLY</span></header>
    {error && <div className="rounded-xl border border-white/15 bg-surface px-4 py-3 text-xs text-text-muted flex justify-between gap-3"><span>{error}</span><button onClick={() => void loadCurrentState()} className="text-primary font-semibold">Retry</button></div>}
    <section className="grid lg:grid-cols-4 gap-4"><div className="lg:col-span-3 bg-surface/80 border border-white/[.08] rounded-2xl p-5"><div className="flex justify-between"><div><p className="text-[10px] text-text-muted uppercase tracking-widest">Current state</p><p className="mt-2 text-white font-semibold">{loading ? 'Loading current metrics…' : status?.primary_issue || 'No current diagnosis available'}</p></div><button onClick={() => void loadCurrentState()} title="Refresh current state" className="p-2 border border-white/[.08] rounded-lg text-text-muted"><RefreshCw className={'h-4 w-4 ' + (loading ? 'animate-spin' : '')} /></button></div>{metrics && status && <div className="mt-4 grid grid-cols-2 md:grid-cols-4 gap-3 text-xs"><div><span className="text-text-muted">CPU</span><p className="text-white font-semibold">{metrics.cpu}%</p></div><div><span className="text-text-muted">Latency</span><p className="text-white font-semibold">{metrics.latency} ms</p></div><div><span className="text-text-muted">Risk</span><p className="text-white font-semibold">{status.risk}</p></div><div><span className="text-text-muted">Source</span><p className="text-white font-semibold">{status.scenario?.label ? 'Synthetic demo' : 'Current telemetry'}</p></div></div>}</div><div className="bg-surface/80 border border-white/[.08] rounded-2xl p-5"><p className="text-[10px] text-text-muted uppercase tracking-widest">Model context</p><p className="mt-2 text-white text-xs">Hybrid anomaly detection, weighted rule analysis, and deterministic simulation.</p></div></section>
    <section className="grid lg:grid-cols-2 gap-6"><div className="bg-surface/80 border border-white/[.08] rounded-2xl p-5"><p className="text-[10px] text-text-muted uppercase tracking-widest">Select action</p><select value={action} onChange={event => setAction(event.target.value)} className="mt-3 w-full bg-background border border-white/[.1] rounded-xl p-3 text-sm text-white">{actions.map(([id, label]) => <option value={id} key={id}>{label}</option>)}</select><p className="mt-3 text-xs text-text-muted">Selected action: <span className="text-white">{selectedLabel}</span></p><button onClick={() => void simulate()} disabled={!metrics || !status || simulating} className="mt-5 w-full py-3 rounded-xl bg-gradient-to-r from-primary to-accent text-background text-xs font-bold disabled:opacity-40 flex justify-center gap-2"><Play className="h-4 w-4 fill-current" />{simulating ? 'Simulating…' : 'Simulate selected action'}</button><p className="mt-3 text-[10px] text-text-muted">No infrastructure is changed by this request.</p></div>
      <div className="bg-surface/80 border border-white/[.08] rounded-2xl p-5"><p className="text-[10px] text-text-muted uppercase tracking-widest">Expected result</p>{result ? <div className="mt-4 space-y-4 text-xs"><div className="flex items-center gap-2 text-accent"><Sparkles className="h-4 w-4" /><span className="font-semibold">SIMULATION RESULT</span></div><p className="text-white leading-relaxed">{result.explanation}</p><div className="grid grid-cols-2 gap-3"><div><span className="text-text-muted">Projected CPU</span><p className="text-white font-semibold">{result.updated_metrics.cpu_usage}%</p></div><div><span className="text-text-muted">Projected latency</span><p className="text-white font-semibold">{result.updated_metrics.latency} ms</p></div><div><span className="text-text-muted">Failure risk</span><p className="text-white font-semibold">{result.failure_risk}</p></div><div><span className="text-text-muted">Confidence</span><p className="text-white font-semibold">{result.confidence} · {formatConfidence(result.confidence_pct)}</p></div></div><div><span className="text-text-muted">Root cause context</span><p className="text-white mt-1">{result.root_cause}</p></div></div> : <div className="h-48 grid place-items-center text-center text-xs text-text-muted"><span>Choose an action to view its expected impact, risk, confidence, and explanation.</span></div>}</div></section>
  </div></div>;
}
